UI/Controllers/CargoInfoController.cs
using Bll;
using DalFactory;
using IBll;
using Model;
using Model.DbQueryModel;
using System.Linq;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class CargoInfoController : BaseController<CargoInfo>
    {
        public IServiceSession ServiceSession => ServiceSessionFactory.GetCurrentServiceSession();

        public ICargoLogInfoService CargoLogInfoService { get; set; }
        public ICargoInfoService CargoInfoService { get; set; }

        public override void SetCurrentService()
        {
            CurrentService = ServiceSession.CargoInfoService;
            CargoLogInfoService = ServiceSession.CargoLogInfoService;
            CargoInfoService = (ICargoInfoService)CurrentService;
        }

        public ActionResult Index()
        {
            var entities = CurrentService.GetAllEntities().OrderByDescending(m => m.Id).ToList();
            var model = ModelHelper<CargoInfo, CargoInfoViewModel>.EntitiesToModels(entities);
            return View(model);
        }

        #region 添加
        public ActionResult Create()
        {
            return View();
        }
        #endregion

        #region 修改
        public ActionResult Edit(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = CurrentService.GetEntityById(id);
            var model = ModelHelper<CargoInfo, CargoInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

        #region 删除
        public ActionResult Delete(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = CurrentService.GetEntityById(id);
            var model = ModelHelper<CargoInfo, CargoInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

    }
}

UI/Controllers/ProjectInfoController.cs
using DalFactory;
using IBll;
using Model;
using Model.DbQueryModel;
using System.Linq;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class ProjectInfoController : BaseController<ProjectInfo>
    {
        public IServiceSession ServiceSession => ServiceSessionFactory.GetCurrentServiceSession();

        public override void SetCurrentService()
        {
            CurrentService = ServiceSession.ProjectInfoService;
        }
      
        public ActionResult Index()
        {
            var entities = CurrentService.GetAllEntities().OrderByDescending(m => m.Id).ToList();
            var model = ModelHelper<ProjectInfo, ProjectInfoViewModel>.EntitiesToModels(entities);
            return View(model);
        }

        #region 添加
        public ActionResult Create()
        {
            return View();
        }
        #endregion

        #region 修改
        public ActionResult Edit(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = CurrentService.GetEntityById(id);
            var model = ModelHelper<ProjectInfo, ProjectInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

        #region 删除
        public ActionResult Delete(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = CurrentService.GetEntityById(id);
            var model = ModelHelper<ProjectInfo, ProjectInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

    }
}

UI/Controllers/SupplyInfoController.cs
using DalFactory;
using IBll;
using Model;
using Model.DbQueryModel;
using System.Linq;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class SupplyInfoController : BaseController<SupplyInfo>
    {

        public IServiceSession ServiceSession => ServiceSessionFactory.GetCurrentServiceSession();

        public override void SetCurrentService()
        {
            CurrentService = ServiceSession.SupplyInfoService;
            CategoryInfoService = ServiceSession.CategoryInfoService;
        }

        public ICategoryInfoService CategoryInfoService { get; set; }

        #region 展示列表
        public ActionResult Index()
        {
            var entities = CurrentService.GetAllEntities().OrderByDescending(m => m.Id).ToList();
            var model = ModelHelper<SupplyInfo, SupplyInfoViewModel>.EntitiesToModels(entities);
            return View(model);
        }
        #endregion

        #region 添加
        public ActionResult Create()
        {
            ViewBag.SupplyName = new SelectList(CategoryInfoService.GetAllEntities(), "Id", "SupplyName", 1);
            return View();
        }
        #endregion

        #region 修改
        public ActionResult Edit(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = CurrentService.GetEntityById(id);
            var model = ModelHelper<SupplyInfo, SupplyInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

        #region 删除
        public ActionResult Delete(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = CurrentService.GetEntityById(id);
            var model = ModelHelper<SupplyInfo, SupplyInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

        #region 添加品种
        public ActionResult AddCategory(int id)
        {
            var entity = CurrentService.GetEntityById(id);
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory()
        {
            //var entity = CurrentService.GetEntityById(id);
            return View();
        }
        #endregion

    }
}

UI/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bll;
using DalFactory;
using IBll;
using Model;
using Model.DbQueryModel;
using Model.ReturnMessageModel;
using Newtonsoft.Json;

namespace UI.Controllers
{
    public class UserInfoController : BaseController<UserInfo>
    {

        public IServiceSession SessionSession => ServiceSessionFactory.GetCurrentServiceSession();
        private readonly UserInfoService _userInfoService = new UserInfoService();
        private readonly UserPrivilegeInfoService _userPrivilegeInfoService = new UserPrivilegeInfoService();

        public override void SetCurrentService()
        {
            CurrentService = SessionSession.UserInfoService;
        }

        #region 登录
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserInfoViewModel model)
        {
            var json = _userInfoService.Login(model.UserName, model.Password);
            return Json(json);
        }
        #endregion

        #region 展示列表
        public ActionResult Index()
        {
            var entities = _userInfoService.GetAllEntities().OrderByDescending(m => m.Id).ToList();
            var model = ModelHelper<UserInfo, UserInfoViewModel>.EntitiesToModels(entities);
            return View(model);
        }
        #endregion

        #region 添加
        public ActionResult Create()
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            return View();
        }
        #endregion

        #region 修改
        public ActionResult Edit(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = _userInfoService.GetEntityById(id);
            var model = ModelHelper<UserInfo, UserInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion

        #region 删除
        public ActionResult Delete(int id)
        {
            //ViewBag.UserPrivilegesId = new SelectList(_db.ProjectInfo, "Id", "ProjectName", 1);
            var entity = _userInfoService.GetEntityById(id);
            var model = ModelHelper<UserInfo, UserInfoViewModel>.EntityToModel(entity);
            return View(model);
        }
        #endregion


        private static object StrToJson(string str)
        {
            return JsonConvert.DeserializeObject(str);
        }

    
    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title MAX</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default box-shadow navbar-fixed-top">
  
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a class="nav-link text-dark" href="@Url.Action("Index", "SupplyInfo")">供应商管理</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" href="@Url.Action("Index", "CategoryInfo")">品种管理</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" href="@Url.Action("Index", "UserInfo")">用户管理</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" href="@Url.Action("Index", "ProjectInfo")">项目管理</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" href="@Url.Action("Index", "CargoInfo")">商品管理</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" href="@Url.Action("Index", "CargoLogInfo")">库存记录</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Belong to Max</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>